### ISSUE TITLE
Llama2-7B-Chat-Augmented Model

### ISSUE THREAD

**Issue by chrisyxue** [Unispac/shallow-vs-deep-alignment#3]
Hi,

Awesome and inspirational work! Are you planning to release the parameters for **Llama2-7B-Chat-Augmented**? Our computing resources are pretty limited to reproducing the finetune procedure.

Looking forward to your reply.

**Comment by Unispac** [comment]
Hi, we have released a checkpoint earlier that we re-implemented on Gemma-2 (https://huggingface.co/Unispac/Gemma-2-9B-IT-With-Deeper-Safety-Alignment).

I will also add the llama-2-augmented checkpoint evaluated in the paper soon.

Thank you.

**Comment by chrisyxue** [comment]
Awesome! Thank you, and please keep me posted!

**Comment by jason-vega** [comment]
Hi, just wanted to follow up on this issue as it appears that Llama2-7B-Chat-Augmented is still not available. Thanks!

**Comment by Unispac** [comment]
Hey, sorry for the delay in following up. After closing this issue, I didn’t receive any follow-up notifications for some reason.

Please find the checkpoint here: https://huggingface.co/Unispac/Llama2-7B-Chat-Augmented/tree/main

But overall, modern models are being updated quickly. Either llama2 or gemma2 we play with are already outdated. Maybe it would be better to just run the data augmentation code on the latest open-source models with our provided data or your own safety data that you like. For 7B or 9B models, it usually takes less than 1 hour on 4 GPUs.

Apologize again for the delay of the reply.
